const plans = {
  rutina:{title:"La rutina que alcanza",intro:"No hace falta lavar fuerte. Hace falta retirar bien la sangre, lavar suave y secar por completo.",steps:[["Enjuagá","Usá agua fría hasta que deje de salir sangre. Presioná suavemente para que el agua atraviese las capas.","AGUA FRÍA"],["Lavá","A mano o en lavarropas junto con tu ropa interior. Elegí un lavado suave y evitá productos abrasivos.","MANO O LAVARROPAS"],["Secá","Colgá y esperá hasta que esté completamente seca antes de guardarla. Evitá fuentes intensas de calor.","SECADO COMPLETO"]],note:"Durante el ciclo, cambiala cada 4 o 5 horas. Si la sangre se seca dentro de las capas, después cuesta más retirarla."},
  primerUso:{title:"Antes de estrenarla",intro:"Un primer lavado higieniza la prenda y ayuda a que las fibras se ablanden.",steps:[["Lavala una vez","Podés hacerlo a mano o en lavarropas, con el mismo cuidado que usarías para tu ropa interior.","ANTES DE USAR"],["Sin castigar las telas","Si lavás a mano, preferí jabón vegetal. Si necesitás cepillo, usá únicamente cerdas suaves.","LAVADO SUAVE"],["Dejala secar","Usala recién cuando todas las capas estén completamente secas.","LISTA PARA USAR"]]},
  mancha:{title:"Rescate de manchas",intro:"Empezá por lo más simple. La mancha no necesita violencia: necesita tiempo y un buen enjuague.",steps:[["Agua fría","Enjuagá de ambos lados hasta que el agua salga limpia. No empieces con calor.","PRIMER PASO"],["Remojo","Dejala al menos 40 minutos en agua fría, sin agregar productos. Después volvé a enjuagar.","40 MINUTOS"],["Lavado final","Lavá a mano o en lavarropas. Si usás Polvo Z, seguí la cantidad y el tiempo indicados en el envase.","ENJUAGÁ MUY BIEN"]],note:"Una sombra tenue no significa que la prenda esté sucia. Evitá frotar con fuerza: puede dañar la superficie antes de mejorar la mancha."},
  olor:{title:"Cuando queda olor",intro:"Lo más frecuente es que haya quedado sangre, producto o humedad retenida entre las capas.",steps:[["Reenjuagá","Pasá abundante agua fría y presioná con suavidad hasta que el agua salga completamente limpia.","SIN APURAR"],["Volvé a lavar","Hacé un lavado suave. Si recurrís a Polvo Z, respetá siempre las indicaciones del envase.","POCO PRODUCTO"],["Secá por completo","No la guardes húmeda, aunque por fuera parezca seca. Las capas internas necesitan más tiempo.","PASO CLAVE"]]},
  guardar:{title:"Lista para el próximo ciclo",intro:"El guardado empieza cuando la prenda ya está limpia, bien enjuagada y seca por dentro.",steps:[["Comprobá","Tocá el centro y los bordes: no debería sentirse humedad ni frío retenido.","100% SECA"],["Cuidá los broches","Abrilos tomándolos con los dedos. No tires de la tela para separarlos.","SIN TIRONES"],["Guardá","Elegí un lugar limpio y seco. Evitá dejarlas comprimidas si todavía conservan humedad.","HASTA EL PRÓXIMO CICLO"]],note:"Con buen uso y cuidado, la vida útil estimada de las toallitas es de 2 a 5 años."}
};
const icons=[`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M12 2s6 7 6 12a6 6 0 1 1-12 0c0-5 6-12 6-12Z"/></svg>`,`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M4 8h16l-1 12H5L4 8ZM7 4h10M8 13c1.2-1.3 2.5-1.3 3.7 0 1.2 1.3 2.5 1.3 3.8 0"/></svg>`,`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M4.9 4.9l1.4 1.4m11.4 11.4 1.4 1.4M2 12h2m16 0h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/></svg>`];
let product="toallita",need="rutina",seconds=2400,running=false,interval=null;
const $=id=>document.getElementById(id);
function render(){const p=plans[need];$("plan-label").textContent=`TU PLAN PARA ${product==="toallita"?"LA TOALLITA":"LA BOMBACHA"}`;$("plan-title").textContent=p.title;$("plan-intro").textContent=p.intro;$("steps").innerHTML=p.steps.map((s,i)=>`<article class="step-card"><div class="step-icon">${icons[i]}</div><span class="step-index">0${i+1}</span><p class="step-tag">${s[2]}</p><h3>${s[0]}</h3><p>${s[1]}</p></article>`).join("");$("product-note").hidden=product!=="bombacha";$("plan-note").hidden=!p.note;$("plan-note").textContent=p.note||"";$("timer").hidden=need!=="mancha";}
document.querySelectorAll("[data-product]").forEach(b=>b.addEventListener("click",()=>{product=b.dataset.product;document.querySelectorAll("[data-product]").forEach(x=>x.classList.toggle("active",x===b));render()}));
document.querySelectorAll("[data-need]").forEach(b=>b.addEventListener("click",()=>{need=b.dataset.need;document.querySelectorAll("[data-need]").forEach(x=>x.classList.toggle("active",x===b));render()}));
function showTime(){$("timer-text").textContent=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`}
$("timer-toggle").addEventListener("click",()=>{running=!running;$("timer-toggle").textContent=running?"Pausar":seconds===2400?"Iniciar 40 min":"Continuar";clearInterval(interval);if(running)interval=setInterval(()=>{if(seconds>0){seconds--;showTime()}else{running=false;clearInterval(interval);$("timer-toggle").textContent="Listo"}},1000)});
$("timer-reset").addEventListener("click",()=>{running=false;clearInterval(interval);seconds=2400;showTime();$("timer-toggle").textContent="Iniciar 40 min"});
render();
